name: filmguru
description: Netguru Flutter recruitment app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  freezed: ^2.5.2
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.3
  dartz: ^0.10.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  build_test: ^2.2.2
  mockito: ^5.4.4
  bloc_test: ^9.1.7


flutter:
  uses-material-design: true

  assets:
    - assets/mock/movies_response.json

flutter_intl:
  enabled: true
